"""add new field to user table

Revision ID: 09865da21a4c
Revises: b8302b1dd428
Create Date: 2023-06-01 15:06:48.575135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09865da21a4c'
down_revision = 'b8302b1dd428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_staff', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_staff')

    # ### end Alembic commands ###
